let datosListado = {
    "aviso1": {
        region: "Región Metropolitana de Santiago ",
        comuna: "Santiago",
        sector: "Parque O'Higgins",
        nombre_contacto: "Chococat",
        email: "chococat@yippeee.cl",
        fono: "+569.12345678",
        metodo_contacto: "Telegram: chococat21",
        tipo: "Gato",
        cantidad: "1",
        edad: "8",
        unidad_medida_edad: "meses",
        fecha_entrega: "2025-07-30 09:00",
        fecha_publicacion: "2025-07-02	21:20",
        descripcion: "Descripción",
        foto: "chococat.jpeg"
    },
    "aviso2": {
        region: "Región Metropolitana de Santiago ",
        comuna: "La Florida",
        sector: "Estadio Bicentenario",
        nombre_contacto: "Waddle Dee",
        email: "waddlewaddle@yippeee.cl",
        fono: "+569.98765432",
        metodo_contacto: "Telegram: waddlewaddle45",
        tipo: "Perro",
        cantidad: "1",
        edad: "3",
        unidad_medida_edad: "meses",
        fecha_entrega: "2025-05-10 13:30",
        fecha_publicacion: "2025-04-09 08:30",
        descripcion: "Descripción",
        foto: "waddle.jpeg"
    },
    "aviso3": {
        region: "Región Metropolitana de Santiago ",
        comuna: "Puente Alto",
        sector: "Ciudad del Este",
        nombre_contacto: "Meta Knight",
        email: "metaknight@yippeee.cl",
        fono: "+569.12349876",
        metodo_contacto: "Instagram: knight",
        tipo: "Gato",
        cantidad: "1",
        edad: "5",
        unidad_medida_edad: "meses",
        fecha_entrega: "2024-07-27 10:00",
        fecha_publicacion: "2024-07-01 13:40",
        descripcion: "Descripción",
        foto: "meta.jpeg"
    },
    "aviso4": {
        region: "Región Metropolitana de Santiago ",
        comuna: "Macul",
        sector: "Estadio Monumental",
        nombre_contacto: "Keroppi",
        email: "keroppi@yippeee.cl",
        fono: "+569.99999999",
        metodo_contacto: "TikTok: kerop80",
        tipo: "Gato",
        cantidad: "1",
        edad: "3",
        unidad_medida_edad: "años",
        fecha_entrega: "2024-07-02 12:00",
        fecha_publicacion: "2024-06-01 20:34",
        descripcion: "Descripción",
        foto: "gato.jpeg"
    },
    "aviso5": {
        region: "Región Metropolitana de Santiago ",
        comuna: "Santiago",
        sector: "Italiano Veloz",
        nombre_contacto: "Heavy Lobster",
        email: "heavylobster@yippeee.cl",
        fono: "+569.77777777",
        metodo_contacto: "Instagram: heavlobst33",
        tipo: "Perro",
        cantidad: "1",
        edad: "2",
        unidad_medida_edad: "años",
        fecha_entrega: "2023-05-12 14:00",
        fecha_publicacion: "2023-02-01 12:43",
        descripcion: "Descripción",
        foto: "kirby.jpeg"
    }
};